spring:
    datasource:
        url: jdbc:mysql://localhost:3366/exposed_study?useSSL=false&serverTimezone=UTC&autoReconnect=true&rewriteBatchedStatements=true&logger=Slf4JLogger&profileSQL=false&maxQuerySizeToLog=100000
        username: root
        password:
        driver-class-name: com.mysql.cj.jdbc.Driver
#        hikari:
#            auto-commit: true
    exposed:
        generate-ddl: true
    #    excluded-packages:

    jpa:
        generate-ddl: true
        hibernate:
            ddl-auto: create

logging.level.Exposed: DEBUG