server:
    port: 8181
spring:
    application:
        name: order-service
#
#    rabbitmq:
#        host: localhost
#        port: 5672
#        username: user
#        password: user

    cloud:
        bus:
            trace:
                enabled: true
    config:
        import: "optional:configserver:http://localhost:8888"

eureka:
    instance:
        prefer-ip-address: true
    client:
        register-with-eureka: true
        fetch-registry: true
        service-url:
            default-zone: http://localhost:8761/eureka/

logging:
    level:
        ROOT: info


management:
    endpoints:
        web:
            exposure:
                include:
                    - "info"
                    - "bus-refresh"
                    - "bus-env"
                    - "health"
                    - "hystrix.stream"
                    - "refresh"
                    - "logger"
    endpoint:
        refresh:
            enabled: true