server:
    port: 8080

spring:
    application:
        name: gateway-service


    cloud:
        gateway:
            routes:
                -   id: licensing-service
                    uri: http://localhost:8082
                    predicates:
                        - Path=/licensing/**
                    filters:
                        - RewritePath=/licensing/(?<path>.*),/$\{path}



management:
    endpoints:
        web:
            exposure:
                include:
                    - "*"