server:
    port: 5555

spring:
    application:
        name: gateway-server

    cloud:
        gateway:
            discovery:
                locator:
                    enabled: false

            httpclient:
                connect-timeout: 10000
                response-timeout: 10s

            default-filters:
                -   name: GlobalFilter
                    args:
                        message: "spring gateway global filter"
                        preLogger: true
                        postLogger: true

            routes:
                -   id: order-service
                    uri: http://localhost:8181
                    predicates:
                        - Path=/order-service/**
                    filters:
                        - RewritePath=/order-service/(?<path>.*),/$\{path}
                        - CustomFilter


                -   id: cart-service
                    uri: http://localhost:8181
                    predicates:
                        - Path=/cart-service/**
                    filters:
                        - RewritePath=/cart-service/(?<path>.*),/$\{path}
                        - CustomFilter

logging:
    level:
        root: info
        reactor.netty.http.server.AccessLog: debug

management:
    endpoints:
        web:
            exposure:
                include:
                    - "info"
                    - "health"
                    - "gateway"
                    - "bus-refresh"
    endpoint:
        gateway:
            enabled: true