server:
    port: 8888

spring:
    application:
        name: config-server
    cloud:
        config:
            server:
                encrypt.enabled: true
                git:
                    uri: https://github.com/cheese10yun/msa-study-sample
                    search-paths:
                        - "licensing-service"
                        - "organization-service"
eureka:
    instance:
        prefer-ip-address: true
    client:
        register-with-eureka: true
        fetch-registry: true
        service-url:
            default-zone: http://localhost:8761/eureka/