version: '3'

services:
  mysql_member:
    container_name: mysql.data-flow
    image: mysql/mysql-server:5.7
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: 'yun-test'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
      - '3366:3306'
    volumes:
      - './volumes/mysql/default:/var/lib/mysql'
    command:
      - 'mysqld'
      - '--character-set-server=utf8mb4'
      - '--collation-server=utf8mb4_unicode_ci'