spring:
    webflux:
        hiddenmethod:
            filter:
                enabled: true

management:
    endpoints:
        web:
            exposure:
                include:
                    - "*"