management:
    endpoints:
        web:
            exposure:
                include:
                    - "*"
#info:
#    build:
#        name: @project.name@
#        description: @project.description@
#        version: @project.version@