server:
    port: 8888

spring:
    profiles:
        active: native

    cloud:
        config:
            server:
                native:
                    search-locations: file:///Users/yun.cheese/yun/blog-sample/msa-koltin/config-server/src/main/resources/config/licensingservice