server:
  port: 8822



spring:
  profiles:
    active: local
  jpa:
    database: h2
    properties.hibernate.dialect: org.hibernate.dialect.H2Dialect

    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
#        use_sql_comments: true

  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      username: sa
      password:
      driver-class-name: org.h2.Driver
    initialization-mode: always

  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 50
        one-indexed-parameters: true

#logging:
#  level:
#    root: info
#    org:
#      hibernate:
#        type: trace