spring:
    main:
        allow-bean-definition-overriding: true
        web-application-type: NONE

    jpa:
        database: mysql
        properties:
            hibernate.hbm2ddl.auto: none
#            hibernate.generate_statistics: true
            hibernate.jdbc.batch_size: 500
#            hibernate.show_sql: true
            hibernate.ddl-auto: create
            hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect

    datasource:
        url: jdbc:mysql://localhost:3366/batch_study?useSSL=false&serverTimezone=UTC&autoReconnect=true&rewriteBatchedStatements=true&rewriteBatchedInserts=true
        username: root
        password:
        driver-class-name: com.mysql.cj.jdbc.Driver
        initialization-mode: never
        hikari:
            maximum-pool-size: 50
            minimum-idle: 25
        dbcp2:
            test-on-borrow: true
            validation-query: select 1
    batch:
        initialize-schema: always
        job:
            names: ${job.name:NONE}
            enabled: true

logging:
    level:
        ROOT: info
        #org.springframework.batch: DEBUG
#        org.hibernate.type.descriptor.sql.BasicBinder: trace
