spring:
  main.allow-bean-definition-overriding: true
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    ROOT: info
#    org.hibernate.type.descriptor.sql.BasicBinder: trace