spring:
    jpa:
        database: h2
        hibernate:
            ddl-auto: create
        open-in-view: true
#        properties:
#            hibernate.format_sql: true
#            hibernate.show_sql: true

management:
    endpoints:
        web:
            exposure:
                include:
                    - "*"

logging:
    level:
        root: info
#        org.hibernate.type.descriptor.sql.BasicBinder: trace