spring:
    main:
        allow-bean-definition-overriding: true
        web-application-type: NONE

    jpa:
        database: mysql
        properties.hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        hibernate:
            ddl-auto: create
        show-sql: true
        properties:

    datasource:
        url: jdbc:mysql://localhost:3366/batch_study?useSSL=false&serverTimezone=UTC&autoReconnect=true
        username: root
        password:
        driver-class-name: com.mysql.cj.jdbc.Driver
        initialization-mode: never
        hikari:
            maximum-pool-size: 20
        dbcp2:
            test-on-borrow: true
            validation-query: select 1
    batch:

        initialize-schema: always
        job:
            names: ${job.name:NONE}

logging:
    level:
        ROOT: info
        #org.springframework.batch: DEBUG
        #org.hibernate.type.descriptor.sql.BasicBinder: trace
