spring:
  batch.job.names: ${job.name:NONE}
  jpa:
    database: mysql
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: create
    show-sql: true
#    properties:
#      hibernate.format_sql: true

  datasource:
    url: jdbc:mysql://localhost:3366/batch?useSSL=false&serverTimezone=UTC&autoReconnect=true
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always
    dbcp2:
      test-on-borrow: true
      validation-query: select 1

logging:
  level:
    ROOT: info
    org:
      hibernate:
        type: trace