server:
    port: 8081

spring:
    application:
        name: organizationservice
    profiles:
        active: default



eureka:
    instance:
        prefer-ip-address: true
    client:
        register-with-eureka: true
        fetch-registry: true
        service-url:
            default-zone: http://localhost:8761/eureka/

management:
    endpoints:
        web:
            exposure:
                include:
                    - "info"
                    - "health"
                    - "refresh"
    endpoint:
        refresh:
            enabled: true