spring:
  main:
    allow-bean-definition-overriding: true
    web-application-type: NONE
  batch:
    initialize-schema: always
    job:
      names: ${job.name:NONE}
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;
    username: root
    password:
    driver-class-name: org.h2.Driver
    initialization-mode: always

logging:
  level:
    ROOT: info
