spring:
    main.allow-bean-definition-overriding: true
    jpa:
        generate-ddl: true
        hibernate:
            ddl-auto: create

    datasource:
        url: jdbc:mysql://localhost:3366/event_transaction?useSSL=false&serverTimezone=UTC&autoReconnect=true
        username: root
        password:
        driver-class-name: com.mysql.cj.jdbc.Driver
        initialization-mode: never