version: "3"
services:
    db_master:
        image: mysql/mysql-server:5.7
        container_name: master
        hostname: master
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_HOST: '%'
            MYSQL_ROOT_PASSWORD: 'root'
        volumes:
            - ./volumes/db/master/data:/var/lib/mysql
            - ./volumes/db/master/log:/var/log/mysql
            - ./volumes/db/master/conf.d:/etc/mysql/conf.d
        networks:
            - mybridge
    db_slave:
        image: mysql/mysql-server:5.7
        container_name: slave
        hostname: slave
        ports:
            - "3307:3306"
        environment:
            MYSQL_ROOT_HOST: '%'
            MYSQL_ROOT_PASSWORD: 'root'
        volumes:
            - ./volumes/db/slave/data:/var/lib/mysql
            - ./volumes/db/master/log:/var/log/mysql
            - ./volumes/db/slave/conf.d:/etc/mysql/conf.d
        networks:
            - mybridge
networks:
    mybridge:
        external: true