server:
    port: 5555

spring:
    application:
        name: gateway-server

    cloud:
        gateway:
            discovery:
                locator:
                    enabled: true
            routes:
                -   id: order-service
                    #                    uri: http://localhost:8181
                    uri: lb://order-service
                    predicates:
                        - Path=/order/**
                    filters:
                        - RewritePath=/order/(?<path>.*),/$\{path}
                        - AddRequestParameter=red, blue
                        - AddRequestHeader=X-Request-red, blue
                        -   name: Retry
                            args:
                                retries: 3
                                statuses: BAD_GATEWAY
                                methods: GET,POST
                                backoff:
                                    firstBackoff: 10ms
                                    maxBackoff: 50ms
                                    factor: 2
                                    basedOnPreviousValue: false
                    metadata:
                        connect-timeout: 10000
                        response-timeout: 10000
                -   id: cart-service
                    #                        uri: http://localhost:8181
                    uri: lb://cart-service
                    predicates:
                        - Path=/cart/**
                    filters:
                        - RewritePath=/cart/(?<path>.*),/$\{path}
                    metadata:
                        connect-timeout: 10000
                        response-timeout: 10000

            httpclient:
                connect-timeout: 20000
                response-timeout: 1s
eureka:
    instance:
        prefer-ip-address: true
    client:
        register-with-eureka: true
        fetch-registry: true
        service-url:
            default-zone: http://localhost:8761/eureka/
logging:
    level:
        root: INFO
        reactor.netty.http.server.AccessLog: INFO

management:
    endpoints:
        web:
            exposure:
                include:
                    - "info"
                    - "health"
                    - "gateway"
                    - "bus-refresh"
    endpoint:
        gateway:
            enabled: true