server:
    port: 5555

spring:
    application:
        name: gateway-server

    cloud:
        gateway:
            routes:
                -   id: order-service
                    uri: http://localhost:8181
                    predicates:
                        - Path=/order/**
                    filters:
                        - RewritePath=/order/(?<path>.*),/$\{path}

management:
    endpoints:
        web:
            exposure:
                include:
                    - "*"