spring:
    redis:
        host: 117.123.112.198
        port: 6379
        password: cheese10


logging:
    level:
        root: INFO
        redis.clients: TRACE
        org.springframework.data: TRACE