spring:
    redis:
        host: 124.80.103.104
        port: 6379
        password: cheese10


logging:
    level:
        root: INFO
        redis.clients: TRACE
        org.springframework.data: TRACE